### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by bevacqua** [markdown-it/uc.micro#6]
Hey @puzrin,

Love all the work you're doing with `markdown-it`. We're using it at work for a commercial project, and `WTFPL` is a bit of a hassle for us, given that big companies [don't like it very much](https://opensource.google.com/docs/thirdparty/licenses/#wtfpl-not-allowed):

> # WTFPL not allowed
> 
> Code released under the WTFPL cannot be used at Google. This license has a large number of issues (lack of warranty disclaimer, very vague rights grant), and was also rejected as an open source license by OSI. We also do not allow contribution to projects under the WTFPL.
> 
> The Beerware license has similar issues.
> 
> See go/whatisalicense for more information on what we look for in a license.

I was wondering if this package could change it's license to `MIT`, and be bumped in both `markdown-it` and `linkify-it`, so that we can keep using the fantastic `markdown-it` project.

Thanks a ton for considering this.
Nico

**Comment by puzrin** [comment]
This licence was selected because i had no time to clarify copyright info :). That's not a big deal since all data is autogenerated. But for MIT we should be more precise.

@mathiasbynens what should be in "copyright" of MIT licence? Formally, this package [use your one](https://github.com/markdown-it/uc.micro/blob/master/update.js#L13-L22).

**Comment by bevacqua** [comment]
@puzrin My understanding is that you can just list MIT as your own license*, then make it clear you're using @mathiasbynens' code (licensed MIT), which you already do, and that's it.

e.g: Copyright Vitaly © 2017 MIT or some such

**Comment by puzrin** [comment]
@bevacqua MIT licence should have "copyright" in the head. I need to know exactly what to place there.

Or someone could rewrite updater to generate data files instead of copying those. But that's overcomplication. I'd prefer to place there anything recommended by @mathiasbynens

**Comment by matschaffer** [comment]
Just noting that https://github.com/mathiasbynens/unicode-9.0.0#license doesn't make a copyright statement, but it references node-unicode-data which [includes a non-dated MIT license](https://github.com/mathiasbynens/node-unicode-data/blob/master/LICENSE-MIT.txt).

Unless @mathiasbynens has other wishes, perhaps `Copyright Mathias Bynens <https://mathiasbynens.be/>` could be a sufficient header?

**Comment by mathiasbynens** [comment]
This package is a subset of the `unicode-x.0.0` package, so I’d expect the upstream license to be respected. @matschaffer’s suggested copyright note + a mention of the MIT license SGTM.

**Comment by puzrin** [comment]
Sorry for silence. Updated everything as suggested. Thanks to @mathiasbynens and @matschaffer for comments.

**Comment by bevacqua** [comment]
cc @andrew-moldovan, we can use markdown again 😅

**Comment by bevacqua** [comment]
Thanks @puzrin!

**Comment by matschaffer** [comment]
So excited!
